### ISSUE TITLE
フィルタが機能しない

### ISSUE THREAD

**Issue by chaco13** [kazu-ux/PixivFilter#55]
pixiv運営が仕様変更をしたからか、非表示機能が利用できないようになりました。

要望
お時間ありましたら、更新していただければと思います。

**Comment by kazu-ux** [comment]
ご報告いただきありがとうございます。さきほど修正を行いました。今後ともよろしくお願い致します。

**Comment by chaco13** [comment]
ご修正いただき、ありがとうございます。
