### ISSUE TITLE
Doesn't work in some search results

### ISSUE THREAD

**Issue by Jao-Yin** [kazu-ux/PixivFilter#59]
First - thank you for making this great program. Yet I found that sometimes filtering doesn't work, and it seems like it happens when I try to search with multiple keywords. I'm not sure about the exact condition of this bug happening, Please check this issue.

**Comment by Jao-Yin** [comment]
Addition - Filtering does not work when a page has a post by username containing dot letter(.).

**Comment by Jao-Yin** [comment]
Addition - Cannot import from json file exported before.

**Comment by kazu-ux** [comment]
Thanks for using this extension.
I've updated it.

**Comment by Jao-Yin** [comment]
Thanks. I'll wait for publish.
