### ISSUE TITLE
Buttons for filtering does not appear in many posts

### ISSUE THREAD

**Issue by Jao-Yin** [kazu-ux/PixivFilter#61]
In many posts in search results the plus sign and triangle next to username does not appear. 
The post which does not show buttons on certain search results can show buttons on other search results showing that post.
Sometimes when there are many posts uploaded by one user some posts show button while some are not.
It seems like even if buttons not appear, filtering works on registered usernames, but not sure.
I'm using version 1.1.0. (Is this the latest version?) This bug appeared after I updated to version 1.1.0.

**Comment by kazu-ux** [comment]
I have not seen that bug on my end.
Could you inform me of the URL where the bug occurs?

**Comment by Jao-Yin** [comment]
Fixed after deleting and reinstalling. Thanks!
