### ISSUE TITLE
何もブロックしたことが無いと、オプションページで "ブロックしたユーザー" と "ブロックしたタグ" の見出しが現れない

### ISSUE THREAD

**Issue by Phroneris** [kazu-ux/PixivFilter#62]
オプションページには「ブロックしたユーザー」と「ブロックしたタグ」という2つの見出しがあると思うのですが、
このPixiv Filterを導入したばかりでまだ何もブロックしたことが無い頃、いずれの見出しも存在しない状態になっていました。

その初期状態のスクリーンショットはちょっと取り損ねたのですが、
タグを1つブロックしてからすぐ削除した時のスクリーンショットがこちらです。
（上辺の灰色部分はChromeのURL欄です。）

<img src="https://user-images.githubusercontent.com/9891867/169848141-ace327e1-fe48-487b-b49f-307a66408902.png" width="400" height="400">

ユーザーをブロックしたことが無いので「ブロックしたユーザー」の見出しは存在せず、
タグをブロックしたことはあるので「ブロックしたタグ」の見出しは出現しています。
初期状態の頃はタグの方の見出しも存在しませんでした。

恐らくはいずれも最初から表示されているべきものだと思いますので、ここに報告します。

**Comment by Phroneris** [comment]
ご対応ありがとうございました。

今更のお節介ですが、コミットやPRのメッセージを書く際に ["fix" 等の特定のキーワード](https://qiita.com/maeda_t/items/d9ef98bf651bd491b16d)をIssue番号と組み合わせて使うと、GitHub上のIssueとコミットを関連付けた上で自動Closeできます。
例えばこちらのコミット→ https://github.com/Phroneris/ReaperJPN-Phroneris/commit/a6d480fdc46019617900d6c583f8cd835014f298 では、1行目に何をしたかを書き、2行目を[Gitのしきたり](https://qiita.com/yu_suke1994/items/29625ad905a5dc5df6c0)で空行にして、3行目に `Fix #番号` と書いて関連付け＆自動Closeを発動させています。

参考になれば幸いです。

**Comment by kazu-ux** [comment]
ありがとうございます！
初心者なので助かります。
