### ISSUE TITLE
ディスカバリー ページでのフィルター

### ISSUE THREAD

**Issue by usbharu** [kazu-ux/PixivFilter#68]
developブランチからで実装しようとしましたが、developブランチで動作しなかったので、要望として書いておきます。

#67 masterブランチで実装したものは動作しました。

**Comment by kazu-ux** [comment]
ご使用いただきありがとうございます。
ディスカバリーページやトップページといった、リロードするごとに表示される作品が大きく異なるページの場合、Chromeの仕様上、作品のタグを取得するのが困難となります。
Firefoxですとその問題が解決されるようですので、Firefoxでの開発も視野に入れております。

**Comment by usbharu** [comment]
topページ、ディスカバリーページともにajaxで取得しているjsonの ```body.thumbnails.illust``` からタグを取得できたと思いますが、それでも困難でしょうか?
的外れなことを言っていたらすみません。

**Comment by kazu-ux** [comment]
はい。そのようなページのjsonはAPIにアクセスするごとにランダムな作品を返してくるため、ページに表示されている作品とは一致しなくなってしまいます。検索ページでは同じjsonを返してくれるので現在の手法が有効でした。
ページを読み込んだ際のjsonを直接使用できれば一番いいのですが、残念ながらChromeの仕様では不可能のようです。

**Comment by usbharu** [comment]
あぁ理解しました。
的外れでしたね。すいません
