### ISSUE TITLE
Brave Browser Problems

### ISSUE THREAD

**Issue by LadyHaywood** [kazu-ux/PixivFilter#76]
I am not able to use the import or export features while using the brave browser. I have tried this on microsoft edge and google chrome and they worked file. The brave browser is a chromium-based browser so I am not sure why nothing happens when I click to import or export a list.

**Comment by kazu-ux** [comment]
See this website.
[https://github.com/brave/brave-browser/issues/20563](https://github.com/brave/brave-browser/issues/20563)

**Comment by LadyHaywood** [comment]
Oh! Thank you for informing me.
