### ISSUE TITLE
Tags feature not working in some posts

### ISSUE THREAD

**Issue by Jao-Yin** [kazu-ux/PixivFilter#77]
Dear kazu, I found in some posts tag blocking is not working. For those posts the tags do not appear when I click the black triangle in a search page. I could not find under what conditions make this. Also I suggest that it would be nice to be blocking tags case-insensitive. Thanks again for making this project.

**Comment by kazu-ux** [comment]
Thank you for your report on the Tag Block feature.
Could you please provide us with more information about the issue? 
This would include:

・The URL of the site where you are experiencing the issue
・The environment you are using (OS, browser, etc.)
・The steps you take to reproduce the issue

We also appreciate your suggestion to make the Tag Block case-insensitive. We will take this into consideration for future improvements to the feature.

**Comment by Jao-Yin** [comment]
Windows 10 version 22H2

**Comment by kazu-ux** [comment]
Thank you.
It appears that works cannot be displayed unless you are logged in to pixiv.
Please log in to pixiv before trying the extension.

**Comment by kazu-ux** [comment]
The extension works fine in my environment.

・Pixiv Filter 1.3.0
・Microsoft Edge 117.0.2045.43
・Windows 10 22H2

Please check that there are no conflicts with other extensions.

**Comment by Jao-Yin** [comment]
I found the condition - it happens when I delete the chrome cache data and go to pixiv after it.

**Comment by kazu-ux** [comment]
It is not intended to work with Incognito Window.

**Comment by Jao-Yin** [comment]
Yep I understand
