### ISSUE TITLE
タグを追加する方法が無い

### ISSUE THREAD

**Issue by spiraldoll** [kazu-ux/PixivFilter#83]
![Screenshot_2024-10-06-20-02-13-90_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/2129c2bb-e3dc-4ea5-9252-6ff283e26ed7)
![Screenshot_2024-10-06-20-02-07-26_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/2a093e1c-b68e-463a-a4f6-f32623c51f7c)
環境は Android 用 Kiwi Browser.

**Comment by spiraldoll** [comment]
![Screenshot_2024-10-06-20-04-21-52_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/14e91f5f-8f0e-4e04-9f5f-bceac7e0ec44)
PC用サイトでも追加する方法が無い。

**Comment by spiraldoll** [comment]
[src/database/chcome_storage.ts](https://github.com/kazu-ux/PixivFilter/blob/master/src/database/chrome_storage.ts)にある機能を、拡張機能設定から直接呼び出せるようにすれば良いのでは。

**Comment by kazu-ux** [comment]
お使いいただきありがとうございます。
検索結果に表示された各作品のユーザー名の右端に三角マーク（▼）を押すことで、その作品のタグ一覧が表示されます。
そして、タグの右にある[+]ボタンを押すと、そのタグをNGに登録できます。
いただいたご意見は開発に活かしてまいります。

**Comment by spiraldoll** [comment]
> 検索結果に表示された各作品のユーザー名の右端に三角マーク（▼）

そんなものは見つかりません。
![Screenshot_2024-11-01-21-39-09-07_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/6249668c-1cfe-42c6-8e40-84c6e77ac207)
![Screenshot_2024-11-01-21-39-46-25_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/0424665b-6df6-4ec9-a86e-b7f63953eb37)
![Screenshot_2024-11-01-21-39-50-81_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/8f72d972-3194-4765-9810-9629a39e0332)
